#!/usr/bin/env python3
"""
notify.py — sends push alerts for unlock and shutdown events.

Uses ntfy.sh (no account needed) over HTTPS. Swap in Firebase/Pusher if
you prefer; keep the same function signature so listener.py doesn't need
to change. Deliberately has zero file-system access — it only makes one
HTTPS request per call.
"""

import time
import urllib.request

_MESSAGES = {
    "unlock_success": ("Laptop Unlocked", "Unlocked via phone at {ts}", "default"),
    "unlock_failed": ("Unlock Attempt Failed", "Rejected unlock attempt at {ts}", "high"),
    "shutdown_triggered": ("Laptop Shutting Down", "Shutdown triggered via phone at {ts}", "urgent"),
    "shutdown_rejected": ("Shutdown Attempt Failed", "Rejected shutdown attempt at {ts}", "high"),
}


def send_alert(kind: str, ntfy_topic: str):
    """`kind` is one of the keys in _MESSAGES above. ntfy_topic comes from
    pairing.json (auto-generated by pair.py as a long random string).
    Treat it like a password — anyone who knows it can read your alerts
    and, more importantly, infer when you're away from your laptop or
    when someone else is attempting to access it."""
    if not ntfy_topic:
        return  # not configured — silently skip rather than error out
    if kind not in _MESSAGES:
        return  # unknown kind — fail silently rather than raise into a caller that never expects this to error

    title, body_template, priority = _MESSAGES[kind]
    body = body_template.format(ts=time.strftime("%Y-%m-%d %H:%M:%S"))

    req = urllib.request.Request(
        f"https://ntfy.sh/{ntfy_topic}",
        data=body.encode(),
        headers={"Title": title, "Priority": priority},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=5):
        pass


# Backwards-compatible wrapper, in case any older script still calls this
# directly by the old name.
def send_unlock_alert(success: bool, ntfy_topic: str):
    send_alert("unlock_success" if success else "unlock_failed", ntfy_topic)
