#!/usr/bin/env python3
"""
notify.py — sends the "your laptop was unlocked" push alert.

Uses ntfy.sh (no account needed) over HTTPS. Swap in Firebase/Pusher if you
prefer; keep the same function signature so listener.py doesn't need to
change. Deliberately has zero file-system access — it only makes one HTTPS
request.
"""

import time
import urllib.request


def send_unlock_alert(success: bool, ntfy_topic: str):
    """ntfy_topic comes from pairing.json (auto-generated by pair.py as a
    long random string). Treat it like a password — anyone who knows it can
    read your unlock alerts and, more importantly, knows when you're
    physically away from your laptop."""
    if not ntfy_topic:
        return  # not configured — silently skip rather than error out

    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    if success:
        title = "Laptop Unlocked"
        body = f"Unlocked via phone at {timestamp}"
        priority = "default"
    else:
        title = "Unlock Attempt Failed"
        body = f"Rejected unlock attempt at {timestamp}"
        priority = "high"

    req = urllib.request.Request(
        f"https://ntfy.sh/{ntfy_topic}",
        data=body.encode(),
        headers={"Title": title, "Priority": priority},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=5):
        pass
